// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenDuoyuwu_screen_init(void)
{
    ui_ScreenDuoyuwu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenDuoyuwu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DuoyuwuBack = lv_img_create(ui_ScreenDuoyuwu);
    lv_img_set_src(ui_DuoyuwuBack, &ui_img_return_png);
    lv_obj_set_width(ui_DuoyuwuBack, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_DuoyuwuBack, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_DuoyuwuBack, -87);
    lv_obj_set_y(ui_DuoyuwuBack, -133);
    lv_obj_set_align(ui_DuoyuwuBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DuoyuwuBack, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_DuoyuwuBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_ScreenDuoyuwu);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -6);
    lv_obj_set_y(ui_Label17, -147);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Result:");

    ui_LabelDuoyuwu = lv_label_create(ui_ScreenDuoyuwu);
    lv_obj_set_width(ui_LabelDuoyuwu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDuoyuwu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDuoyuwu, 0);
    lv_obj_set_y(ui_LabelDuoyuwu, -129);
    lv_obj_set_align(ui_LabelDuoyuwu, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDuoyuwu, "choupicture");
    lv_obj_set_style_text_color(ui_LabelDuoyuwu, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDuoyuwu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SendDuoyuwu = lv_label_create(ui_ScreenDuoyuwu);
    lv_obj_set_width(ui_SendDuoyuwu, 100);
    lv_obj_set_height(ui_SendDuoyuwu, 70);
    lv_obj_set_x(ui_SendDuoyuwu, 56);
    lv_obj_set_y(ui_SendDuoyuwu, 115);
    lv_obj_set_align(ui_SendDuoyuwu, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SendDuoyuwu, "\nSend");
    lv_obj_add_flag(ui_SendDuoyuwu, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_SendDuoyuwu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SendDuoyuwu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SendDuoyuwu, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SendDuoyuwu, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SendDuoyuwu, lv_color_hex(0x838183), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SendDuoyuwu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CheckDuoyuwu = lv_label_create(ui_ScreenDuoyuwu);
    lv_obj_set_width(ui_CheckDuoyuwu, 100);
    lv_obj_set_height(ui_CheckDuoyuwu, 70);
    lv_obj_set_x(ui_CheckDuoyuwu, -60);
    lv_obj_set_y(ui_CheckDuoyuwu, 115);
    lv_obj_set_align(ui_CheckDuoyuwu, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CheckDuoyuwu, "\nCheck");
    lv_obj_add_flag(ui_CheckDuoyuwu, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_CheckDuoyuwu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CheckDuoyuwu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CheckDuoyuwu, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CheckDuoyuwu, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CheckDuoyuwu, lv_color_hex(0x828282), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CheckDuoyuwu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DuoyuwuNext = lv_img_create(ui_ScreenDuoyuwu);
    lv_img_set_src(ui_DuoyuwuNext, &ui_img_906722072);
    lv_obj_set_width(ui_DuoyuwuNext, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_DuoyuwuNext, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_DuoyuwuNext, 86);
    lv_obj_set_y(ui_DuoyuwuNext, -127);
    lv_obj_set_align(ui_DuoyuwuNext, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DuoyuwuNext, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_DuoyuwuNext, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_img_create(ui_ScreenDuoyuwu);
    lv_img_set_src(ui_Image6, &ui_img_dyw5_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 110
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 110
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_DuoyuwuBack, ui_event_DuoyuwuBack, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SendDuoyuwu, ui_event_SendDuoyuwu, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CheckDuoyuwu, ui_event_CheckDuoyuwu, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DuoyuwuNext, ui_event_DuoyuwuNext, LV_EVENT_ALL, NULL);

}
