// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenWelcome_screen_init(void)
{
    ui_ScreenWelcome = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenWelcome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelWelcome1 = lv_label_create(ui_ScreenWelcome);
    lv_obj_set_width(ui_LabelWelcome1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWelcome1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWelcome1, 0);
    lv_obj_set_y(ui_LabelWelcome1, -80);
    lv_obj_set_align(ui_LabelWelcome1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWelcome1, "Welcome");
    lv_obj_set_style_text_font(ui_LabelWelcome1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar2 = lv_bar_create(ui_ScreenWelcome);
    lv_obj_set_width(ui_Bar2, 150);
    lv_obj_set_height(ui_Bar2, 22);
    lv_obj_set_x(ui_Bar2, 4);
    lv_obj_set_y(ui_Bar2, 87);
    lv_obj_set_align(ui_Bar2, LV_ALIGN_CENTER);

    ui_Panel1 = lv_obj_create(ui_ScreenWelcome);
    lv_obj_set_width(ui_Panel1, 5);
    lv_obj_set_height(ui_Panel1, 22);
    lv_obj_set_x(ui_Panel1, 4);
    lv_obj_set_y(ui_Panel1, 87);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xA5A6A5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_ScreenWelcome);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 6);
    lv_obj_set_y(ui_Label4, 64);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "loading...");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScreenWelcome, ui_event_ScreenWelcome, LV_EVENT_ALL, NULL);

}
