// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenWifisetting_screen_init(void)
{
    ui_ScreenWifisetting = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenWifisetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_ScreenWifisetting);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -22);
    lv_obj_set_y(ui_Label7, -13);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Click to connect");

    ui_TextAreaPassword = lv_textarea_create(ui_ScreenWifisetting);
    lv_obj_set_width(ui_TextAreaPassword, 150);
    lv_obj_set_height(ui_TextAreaPassword, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_TextAreaPassword, 40);
    lv_obj_set_y(ui_TextAreaPassword, -68);
    lv_obj_set_align(ui_TextAreaPassword, LV_ALIGN_CENTER);
    lv_textarea_set_one_line(ui_TextAreaPassword, true);
    lv_textarea_set_password_mode(ui_TextAreaPassword, true);
    lv_obj_set_style_border_color(ui_TextAreaPassword, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextAreaPassword, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TextAreaPassword, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardPassword = lv_keyboard_create(ui_ScreenWifisetting);
    lv_keyboard_set_mode(ui_KeyboardPassword, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_KeyboardPassword, 232);
    lv_obj_set_height(ui_KeyboardPassword, 120);
    lv_obj_set_x(ui_KeyboardPassword, 0);
    lv_obj_set_y(ui_KeyboardPassword, 99);
    lv_obj_set_align(ui_KeyboardPassword, LV_ALIGN_CENTER);

    ui_Label10 = lv_label_create(ui_ScreenWifisetting);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -76);
    lv_obj_set_y(ui_Label10, -92);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Account:  ");

    ui_Label11 = lv_label_create(ui_ScreenWifisetting);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -79);
    lv_obj_set_y(ui_Label11, -68);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Password:");

    ui_TextAreaAccount = lv_textarea_create(ui_ScreenWifisetting);
    lv_obj_set_width(ui_TextAreaAccount, 150);
    lv_obj_set_height(ui_TextAreaAccount, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextAreaAccount, 40);
    lv_obj_set_y(ui_TextAreaAccount, -90);
    lv_obj_set_align(ui_TextAreaAccount, LV_ALIGN_CENTER);
    lv_textarea_set_one_line(ui_TextAreaAccount, true);
    lv_obj_set_style_border_color(ui_TextAreaAccount, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextAreaAccount, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TextAreaAccount, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_TextAreaAccount, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextAreaAccount, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TextAreaAccount, 1, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_KeyboardAccount = lv_keyboard_create(ui_ScreenWifisetting);
    lv_keyboard_set_mode(ui_KeyboardAccount, LV_KEYBOARD_MODE_TEXT_UPPER);
    lv_obj_set_width(ui_KeyboardAccount, 234);
    lv_obj_set_height(ui_KeyboardAccount, 120);
    lv_obj_set_x(ui_KeyboardAccount, 0);
    lv_obj_set_y(ui_KeyboardAccount, 98);
    lv_obj_set_align(ui_KeyboardAccount, LV_ALIGN_CENTER);

    ui_ImageConnect = lv_img_create(ui_ScreenWifisetting);
    lv_img_set_src(ui_ImageConnect, &ui_img_410347302);
    lv_obj_set_width(ui_ImageConnect, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_ImageConnect, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_ImageConnect, 79);
    lv_obj_set_y(ui_ImageConnect, -13);
    lv_obj_set_align(ui_ImageConnect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageConnect, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_ImageConnect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image11 = lv_img_create(ui_ScreenWifisetting);
    lv_img_set_src(ui_Image11, &ui_img_return_png);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image11, -87);
    lv_obj_set_y(ui_Image11, -133);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_ScreenWifisetting);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 29);
    lv_obj_set_y(ui_Label8, -133);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Wifi Setting");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_TextAreaPassword, ui_event_TextAreaPassword, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaAccount, ui_event_TextAreaAccount, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImageConnect, ui_event_ImageConnect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image11, ui_event_Image11, LV_EVENT_ALL, NULL);

}
