// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenPWIncorrect_screen_init(void)
{
    ui_ScreenPWIncorrect = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenPWIncorrect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelPWIncorrect = lv_label_create(ui_ScreenPWIncorrect);
    lv_obj_set_width(ui_LabelPWIncorrect, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPWIncorrect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelPWIncorrect, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPWIncorrect, "Password\nIncorrect!");
    lv_obj_set_style_text_font(ui_LabelPWIncorrect, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScreenPWIncorrect, ui_event_ScreenPWIncorrect, LV_EVENT_ALL, NULL);

}
