// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenConnected_screen_init(void)
{
    ui_ScreenConnected = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenConnected, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelConnected = lv_label_create(ui_ScreenConnected);
    lv_obj_set_width(ui_LabelConnected, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelConnected, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelConnected, -2);
    lv_obj_set_y(ui_LabelConnected, -4);
    lv_obj_set_align(ui_LabelConnected, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelConnected, "Connected!");
    lv_obj_set_style_text_font(ui_LabelConnected, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScreenConnected, ui_event_ScreenConnected, LV_EVENT_ALL, NULL);

}
