// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenOption_screen_init(void)
{
    ui_ScreenOption = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenOption, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_ScreenOption);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_ScreenOption);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_img_create(ui_ScreenOption);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_img_create(ui_ScreenOption);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageWifi = lv_img_create(ui_ScreenOption);
    lv_img_set_src(ui_ImageWifi, &ui_img_wifi_png);
    lv_obj_set_width(ui_ImageWifi, 64);
    lv_obj_set_height(ui_ImageWifi, 64);
    lv_obj_set_x(ui_ImageWifi, 0);
    lv_obj_set_y(ui_ImageWifi, -104);
    lv_obj_set_align(ui_ImageWifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageWifi, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_ScreenOption);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, -56);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "WifiSetting");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageFace = lv_img_create(ui_ScreenOption);
    lv_img_set_src(ui_ImageFace, &ui_img_263744089);
    lv_obj_set_width(ui_ImageFace, 64);
    lv_obj_set_height(ui_ImageFace, 64);
    lv_obj_set_x(ui_ImageFace, 0);
    lv_obj_set_y(ui_ImageFace, -7);
    lv_obj_set_align(ui_ImageFace, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageFace, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_ImageFace, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_ScreenOption);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, 32);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "FaceReco");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImagePic = lv_img_create(ui_ScreenOption);
    lv_img_set_src(ui_ImagePic, &ui_img_image_png);
    lv_obj_set_width(ui_ImagePic, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_ImagePic, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_ImagePic, 0);
    lv_obj_set_y(ui_ImagePic, 80);
    lv_obj_set_align(ui_ImagePic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImagePic, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImagePic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_ScreenOption);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -2);
    lv_obj_set_y(ui_Label13, 99);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "");

    ui_Label14 = lv_label_create(ui_ScreenOption);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 0);
    lv_obj_set_y(ui_Label14, 125);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "PicReco");

    lv_obj_add_event_cb(ui_ImageWifi, ui_event_ImageWifi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImageFace, ui_event_ImageFace, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImagePic, ui_event_ImagePic, LV_EVENT_ALL, NULL);

}
