// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenCam_screen_init(void)
{
    ui_ScreenCam = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenCam, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_ScreenCam);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 21);
    lv_obj_set_y(ui_Label3, -141);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Result:");

    ui_ImageCamBack = lv_img_create(ui_ScreenCam);
    lv_img_set_src(ui_ImageCamBack, &ui_img_return_png);
    lv_obj_set_width(ui_ImageCamBack, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_ImageCamBack, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_ImageCamBack, -87);
    lv_obj_set_y(ui_ImageCamBack, -133);
    lv_obj_set_align(ui_ImageCamBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageCamBack, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageCamBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelPeople = lv_label_create(ui_ScreenCam);
    lv_obj_set_width(ui_LabelPeople, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPeople, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPeople, 27);
    lv_obj_set_y(ui_LabelPeople, -116);
    lv_obj_set_align(ui_LabelPeople, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPeople, "choupeople");
    lv_obj_set_style_text_color(ui_LabelPeople, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPeople, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImageCamBack, ui_event_ImageCamBack, LV_EVENT_ALL, NULL);

}
