// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenHuashang_screen_init(void)
{
    ui_ScreenHuashang = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenHuashang, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HuashangBack = lv_img_create(ui_ScreenHuashang);
    lv_img_set_src(ui_HuashangBack, &ui_img_return_png);
    lv_obj_set_width(ui_HuashangBack, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_HuashangBack, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_HuashangBack, -87);
    lv_obj_set_y(ui_HuashangBack, -133);
    lv_obj_set_align(ui_HuashangBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HuashangBack, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HuashangBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_ScreenHuashang);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -6);
    lv_obj_set_y(ui_Label2, -147);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Result:");

    ui_LabelHuashang = lv_label_create(ui_ScreenHuashang);
    lv_obj_set_width(ui_LabelHuashang, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHuashang, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHuashang, 0);
    lv_obj_set_y(ui_LabelHuashang, -129);
    lv_obj_set_align(ui_LabelHuashang, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHuashang, "choupicture");
    lv_obj_set_style_text_color(ui_LabelHuashang, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHuashang, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SendHuashang = lv_label_create(ui_ScreenHuashang);
    lv_obj_set_width(ui_SendHuashang, 100);
    lv_obj_set_height(ui_SendHuashang, 70);
    lv_obj_set_x(ui_SendHuashang, 56);
    lv_obj_set_y(ui_SendHuashang, 115);
    lv_obj_set_align(ui_SendHuashang, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SendHuashang, "\nSend");
    lv_obj_add_flag(ui_SendHuashang, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_SendHuashang, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SendHuashang, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SendHuashang, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SendHuashang, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SendHuashang, lv_color_hex(0x838183), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SendHuashang, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CheckHuashang = lv_label_create(ui_ScreenHuashang);
    lv_obj_set_width(ui_CheckHuashang, 100);
    lv_obj_set_height(ui_CheckHuashang, 70);
    lv_obj_set_x(ui_CheckHuashang, -60);
    lv_obj_set_y(ui_CheckHuashang, 115);
    lv_obj_set_align(ui_CheckHuashang, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CheckHuashang, "\nCheck");
    lv_obj_add_flag(ui_CheckHuashang, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_CheckHuashang, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CheckHuashang, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CheckHuashang, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CheckHuashang, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CheckHuashang, lv_color_hex(0x828282), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CheckHuashang, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HuashangNext = lv_img_create(ui_ScreenHuashang);
    lv_img_set_src(ui_HuashangNext, &ui_img_906722072);
    lv_obj_set_width(ui_HuashangNext, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_HuashangNext, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_HuashangNext, 86);
    lv_obj_set_y(ui_HuashangNext, -127);
    lv_obj_set_align(ui_HuashangNext, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HuashangNext, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HuashangNext, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_img_create(ui_ScreenHuashang);
    lv_img_set_src(ui_Image7, &ui_img_huashang338_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 110
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 110
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_HuashangBack, ui_event_HuashangBack, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SendHuashang, ui_event_SendHuashang, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CheckHuashang, ui_event_CheckHuashang, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HuashangNext, ui_event_HuashangNext, LV_EVENT_ALL, NULL);

}
