// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
///////////////////// extern //////////////////////////////////////////////////////////////////

#include "shell.h"

extern void camera_init_task(void *pvParameters);
extern void camera_start_task(void *pvParameters);
extern camera_start_task_handle;
extern camera_init_task_handle;
extern bool disp_face_result_flag;
extern char send_command[32];
extern bool send_cmd_flag;

///////////////////// VARIABLES ////////////////////
void loading_Animation(lv_obj_t * TargetObject, int delay);
void loading2_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_ScreenWelcome
void ui_ScreenWelcome_screen_init(void);
void ui_event_ScreenWelcome(lv_event_t * e);
lv_obj_t * ui_ScreenWelcome;
lv_obj_t * ui_LabelWelcome1;
lv_obj_t * ui_Bar2;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Label4;

// SCREEN: ui_ScreenOption
void ui_ScreenOption_screen_init(void);
lv_obj_t * ui_ScreenOption;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Image5;
lv_obj_t * ui_Image8;
void ui_event_ImageWifi(lv_event_t * e);
lv_obj_t * ui_ImageWifi;
lv_obj_t * ui_Label5;
void ui_event_ImageFace(lv_event_t * e);
lv_obj_t * ui_ImageFace;
lv_obj_t * ui_Label6;
void ui_event_ImagePic(lv_event_t * e);
lv_obj_t * ui_ImagePic;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Label14;

// SCREEN: ui_ScreenWifisetting
void ui_ScreenWifisetting_screen_init(void);
lv_obj_t * ui_ScreenWifisetting;
lv_obj_t * ui_Label7;
void ui_event_TextAreaPassword(lv_event_t * e);
lv_obj_t * ui_TextAreaPassword;
lv_obj_t * ui_KeyboardPassword;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label11;
void ui_event_TextAreaAccount(lv_event_t * e);
lv_obj_t * ui_TextAreaAccount;
lv_obj_t * ui_KeyboardAccount;
void ui_event_ImageConnect(lv_event_t * e);
lv_obj_t * ui_ImageConnect;
void ui_event_Image11(lv_event_t * e);
lv_obj_t * ui_Image11;
lv_obj_t * ui_Label8;

// SCREEN: ui_ScreenConnected
void ui_ScreenConnected_screen_init(void);
void ui_event_ScreenConnected(lv_event_t * e);
lv_obj_t * ui_ScreenConnected;
lv_obj_t * ui_LabelConnected;

// SCREEN: ui_ScreenCam
void ui_ScreenCam_screen_init(void);
lv_obj_t * ui_ScreenCam;
lv_obj_t * ui_Label3;
void ui_event_ImageCamBack(lv_event_t * e);
lv_obj_t * ui_ImageCamBack;
lv_obj_t * ui_LabelPeople;

// SCREEN: ui_ScreenPWIncorrect
void ui_ScreenPWIncorrect_screen_init(void);
void ui_event_ScreenPWIncorrect(lv_event_t * e);
lv_obj_t * ui_ScreenPWIncorrect;
lv_obj_t * ui_LabelPWIncorrect;

// SCREEN: ui_ScreenDuoyuwu
void ui_ScreenDuoyuwu_screen_init(void);
lv_obj_t * ui_ScreenDuoyuwu;
void ui_event_DuoyuwuBack(lv_event_t * e);
lv_obj_t * ui_DuoyuwuBack;
lv_obj_t * ui_Label17;
lv_obj_t * ui_LabelDuoyuwu;
void ui_event_SendDuoyuwu(lv_event_t * e);
lv_obj_t * ui_SendDuoyuwu;
void ui_event_CheckDuoyuwu(lv_event_t * e);
lv_obj_t * ui_CheckDuoyuwu;
void ui_event_DuoyuwuNext(lv_event_t * e);
lv_obj_t * ui_DuoyuwuNext;
lv_obj_t * ui_Image6;

// SCREEN: ui_ScreenBiankuang
void ui_ScreenBiankuang_screen_init(void);
lv_obj_t * ui_ScreenBiankuang;
void ui_event_BiankuangBack(lv_event_t * e);
lv_obj_t * ui_BiankuangBack;
lv_obj_t * ui_Label1;
lv_obj_t * ui_LabelBiankuang;
void ui_event_SendBiankuang(lv_event_t * e);
lv_obj_t * ui_SendBiankuang;
void ui_event_CheckBiankuang(lv_event_t * e);
lv_obj_t * ui_CheckBiankuang;
void ui_event_BiankuangNext(lv_event_t * e);
lv_obj_t * ui_BiankuangNext;
lv_obj_t * ui_Image4;

// SCREEN: ui_ScreenHuashang
void ui_ScreenHuashang_screen_init(void);
lv_obj_t * ui_ScreenHuashang;
void ui_event_HuashangBack(lv_event_t * e);
lv_obj_t * ui_HuashangBack;
lv_obj_t * ui_Label2;
lv_obj_t * ui_LabelHuashang;
void ui_event_SendHuashang(lv_event_t * e);
lv_obj_t * ui_SendHuashang;
void ui_event_CheckHuashang(lv_event_t * e);
lv_obj_t * ui_CheckHuashang;
void ui_event_HuashangNext(lv_event_t * e);
lv_obj_t * ui_HuashangNext;
lv_obj_t * ui_Image7;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_biankuang[1] = {&ui_img_biankuang241_png};
const lv_img_dsc_t * ui_imgset_dyw[1] = {&ui_img_dyw5_png};
const lv_img_dsc_t * ui_imgset_huashang[1] = {&ui_img_huashang338_png};
const lv_img_dsc_t * ui_imgset_new[1] = {&ui_img_new1_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void loading_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_width);
    lv_anim_set_values(&PropertyAnimation_0, 0, 145);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_width);
    lv_anim_start(&PropertyAnimation_0);

}
void loading2_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_width);
    lv_anim_set_values(&PropertyAnimation_0, 0, 145);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_width);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_ScreenWelcome(lv_event_t * e)//////////////////////////////////////////////////////////////////////////////////////////////////////////////////
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        loading_Animation(ui_Panel1, 50);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_ScreenOption, LV_SCR_LOAD_ANIM_FADE_ON, 500, 1000, &ui_ScreenOption_screen_init);

        /* 默认密码 */
        lv_textarea_set_text(ui_TextAreaAccount,"Mk");
        lv_textarea_set_text(ui_TextAreaPassword,"12345678");
    
    
    }
}
void ui_event_ImageWifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScreenWifisetting, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenWifisetting_screen_init);
    }
}
void ui_event_ImageFace(lv_event_t * e)//////////////////////////////////////////////////////////////////////////////////////////////////////////////////
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScreenCam, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ScreenCam_screen_init);

         /* 得数据 */
        shell_exec_command("mqtt_sub");
        
        vTaskResume(camera_init_task_handle);
        vTaskResume(camera_start_task_handle);

        disp_face_result_flag = 1;

    }
}
void ui_event_ImagePic(lv_event_t * e)//////////////////////////////////////////////////////////////////////////////////////////////////////////////////
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScreenDuoyuwu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenDuoyuwu_screen_init);
    
        shell_exec_command("mqtt_pub");
    }
}
void ui_event_TextAreaPassword(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_keyboard_set_target(ui_KeyboardPassword,  ui_TextAreaPassword);
        _ui_flag_modify(ui_KeyboardAccount, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_KeyboardPassword, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_TextAreaAccount(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_keyboard_set_target(ui_KeyboardAccount,  ui_TextAreaAccount);
        _ui_flag_modify(ui_KeyboardAccount, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_KeyboardPassword, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_ImageConnect(lv_event_t * e)//////////////////////////////////////////////////////////////////////////////////////////////////////////////////
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        
        /* 联网 */
        char* account = lv_textarea_get_text(ui_TextAreaAccount);
        char* password = lv_textarea_get_text(ui_TextAreaPassword);
        
        char* wifi_info = "wifi_sta_connect ";
        strcat(wifi_info, account);
        strcat(wifi_info, " ");
        strcat(wifi_info, password);

        shell_exec_command(wifi_info); //上电自动联网，在shell_freertos.c里添加了这个函数20230717
        
        _ui_screen_change(&ui_ScreenConnected, LV_SCR_LOAD_ANIM_FADE_ON, 500, 500, &ui_ScreenConnected_screen_init);
    }
}
void ui_event_Image11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScreenOption, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenOption_screen_init);
    }
}
void ui_event_ScreenConnected(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_ScreenOption, LV_SCR_LOAD_ANIM_FADE_ON, 1500, 2000, &ui_ScreenOption_screen_init);
    }
}
void ui_event_ImageCamBack(lv_event_t * e)//////////////////////////////////////////////////////////////////////////////////////////////////////////////////
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {

        vTaskSuspend(camera_start_task_handle);
        disp_face_result_flag = 0;

        test_close_face(SHELL_SIGINT);//关闭人脸结果的接收

        _ui_screen_change(&ui_ScreenOption, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScreenOption_screen_init);
    }
}
void ui_event_ScreenPWIncorrect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_ScreenWifisetting, LV_SCR_LOAD_ANIM_FADE_ON, 500, 2000, &ui_ScreenWifisetting_screen_init);
    }
}
void ui_event_DuoyuwuBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScreenOption, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScreenOption_screen_init);
    }
}
void ui_event_SendDuoyuwu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        char* temp = "send_000001.jpg";
        sprintf(send_command, temp, strlen(temp));
        send_cmd_flag = 1;
    }
}
void ui_event_CheckDuoyuwu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        
        memset(send_command, 0, sizeof(send_command));
        char* temp = "detect_000001.jpg";
        sprintf(send_command, temp, strlen(temp));
        send_cmd_flag = 1;
    }
}
void ui_event_DuoyuwuNext(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScreenBiankuang, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenBiankuang_screen_init);
    }
}
void ui_event_BiankuangBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScreenOption, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScreenOption_screen_init);
    }
}
void ui_event_SendBiankuang(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        memset(send_command, 0, sizeof(send_command));
        char* temp = "send_000002.jpg";
        sprintf(send_command, temp, strlen(temp));
        send_cmd_flag = 1;
    }
}
void ui_event_CheckBiankuang(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {

        memset(send_command, 0, sizeof(send_command));
        char* temp = "detect_000002.jpg";
        sprintf(send_command, temp, strlen(temp));
        send_cmd_flag = 1;
    }
}
void ui_event_BiankuangNext(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScreenHuashang, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenHuashang_screen_init);
    }
}
void ui_event_HuashangBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScreenOption, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScreenOption_screen_init);
    }
}
void ui_event_SendHuashang(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        memset(send_command, 0, sizeof(send_command));
        char* temp = "send_000003.jpg";
        sprintf(send_command, temp, strlen(temp));
        send_cmd_flag = 1;
    }
}
void ui_event_CheckHuashang(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        memset(send_command, 0, sizeof(send_command));
        char* temp = "detect_000003.jpg";
        sprintf(send_command, temp, strlen(temp));
        send_cmd_flag = 1;
    }
}
void ui_event_HuashangNext(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScreenDuoyuwu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenDuoyuwu_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_basic_init(dispp);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenWelcome_screen_init();
    ui_ScreenOption_screen_init();
    ui_ScreenWifisetting_screen_init();
    ui_ScreenConnected_screen_init();
    ui_ScreenCam_screen_init();
    ui_ScreenPWIncorrect_screen_init();
    ui_ScreenDuoyuwu_screen_init();
    ui_ScreenBiankuang_screen_init();
    ui_ScreenHuashang_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenWelcome);
}
