// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
void loading_Animation(lv_obj_t * TargetObject, int delay);
void loading2_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_ScreenWelcome
void ui_ScreenWelcome_screen_init(void);
void ui_event_ScreenWelcome(lv_event_t * e);
extern lv_obj_t * ui_ScreenWelcome;
extern lv_obj_t * ui_LabelWelcome1;
extern lv_obj_t * ui_Bar2;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label4;
// SCREEN: ui_ScreenOption
void ui_ScreenOption_screen_init(void);
extern lv_obj_t * ui_ScreenOption;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image8;
void ui_event_ImageWifi(lv_event_t * e);
extern lv_obj_t * ui_ImageWifi;
extern lv_obj_t * ui_Label5;
void ui_event_ImageFace(lv_event_t * e);
extern lv_obj_t * ui_ImageFace;
extern lv_obj_t * ui_Label6;
void ui_event_ImagePic(lv_event_t * e);
extern lv_obj_t * ui_ImagePic;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
// SCREEN: ui_ScreenWifisetting
void ui_ScreenWifisetting_screen_init(void);
extern lv_obj_t * ui_ScreenWifisetting;
extern lv_obj_t * ui_Label7;
void ui_event_TextAreaPassword(lv_event_t * e);
extern lv_obj_t * ui_TextAreaPassword;
extern lv_obj_t * ui_KeyboardPassword;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
void ui_event_TextAreaAccount(lv_event_t * e);
extern lv_obj_t * ui_TextAreaAccount;
extern lv_obj_t * ui_KeyboardAccount;
void ui_event_ImageConnect(lv_event_t * e);
extern lv_obj_t * ui_ImageConnect;
void ui_event_Image11(lv_event_t * e);
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Label8;
// SCREEN: ui_ScreenConnected
void ui_ScreenConnected_screen_init(void);
void ui_event_ScreenConnected(lv_event_t * e);
extern lv_obj_t * ui_ScreenConnected;
extern lv_obj_t * ui_LabelConnected;
// SCREEN: ui_ScreenCam
void ui_ScreenCam_screen_init(void);
extern lv_obj_t * ui_ScreenCam;
extern lv_obj_t * ui_Label3;
void ui_event_ImageCamBack(lv_event_t * e);
extern lv_obj_t * ui_ImageCamBack;
extern lv_obj_t * ui_LabelPeople;
// SCREEN: ui_ScreenPWIncorrect
void ui_ScreenPWIncorrect_screen_init(void);
void ui_event_ScreenPWIncorrect(lv_event_t * e);
extern lv_obj_t * ui_ScreenPWIncorrect;
extern lv_obj_t * ui_LabelPWIncorrect;
// SCREEN: ui_ScreenDuoyuwu
void ui_ScreenDuoyuwu_screen_init(void);
extern lv_obj_t * ui_ScreenDuoyuwu;
void ui_event_DuoyuwuBack(lv_event_t * e);
extern lv_obj_t * ui_DuoyuwuBack;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_LabelDuoyuwu;
void ui_event_SendDuoyuwu(lv_event_t * e);
extern lv_obj_t * ui_SendDuoyuwu;
void ui_event_CheckDuoyuwu(lv_event_t * e);
extern lv_obj_t * ui_CheckDuoyuwu;
void ui_event_DuoyuwuNext(lv_event_t * e);
extern lv_obj_t * ui_DuoyuwuNext;
extern lv_obj_t * ui_Image6;
// SCREEN: ui_ScreenBiankuang
void ui_ScreenBiankuang_screen_init(void);
extern lv_obj_t * ui_ScreenBiankuang;
void ui_event_BiankuangBack(lv_event_t * e);
extern lv_obj_t * ui_BiankuangBack;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_LabelBiankuang;
void ui_event_SendBiankuang(lv_event_t * e);
extern lv_obj_t * ui_SendBiankuang;
void ui_event_CheckBiankuang(lv_event_t * e);
extern lv_obj_t * ui_CheckBiankuang;
void ui_event_BiankuangNext(lv_event_t * e);
extern lv_obj_t * ui_BiankuangNext;
extern lv_obj_t * ui_Image4;
// SCREEN: ui_ScreenHuashang
void ui_ScreenHuashang_screen_init(void);
extern lv_obj_t * ui_ScreenHuashang;
void ui_event_HuashangBack(lv_event_t * e);
extern lv_obj_t * ui_HuashangBack;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_LabelHuashang;
void ui_event_SendHuashang(lv_event_t * e);
extern lv_obj_t * ui_SendHuashang;
void ui_event_CheckHuashang(lv_event_t * e);
extern lv_obj_t * ui_CheckHuashang;
void ui_event_HuashangNext(lv_event_t * e);
extern lv_obj_t * ui_HuashangNext;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_wifi_png);    // assets\wifi.png
LV_IMG_DECLARE(ui_img_263744089);    // assets\face-id.png
LV_IMG_DECLARE(ui_img_image_png);    // assets\image.png
LV_IMG_DECLARE(ui_img_410347302);    // assets\press-button.png
LV_IMG_DECLARE(ui_img_return_png);    // assets\return.png
LV_IMG_DECLARE(ui_img_906722072);    // assets\arrow-right.png
LV_IMG_DECLARE(ui_img_dyw5_png);    // assets\dyw5.png
LV_IMG_DECLARE(ui_img_biankuang241_png);    // assets\biankuang241.png
LV_IMG_DECLARE(ui_img_huashang338_png);    // assets\huashang338.png
LV_IMG_DECLARE(ui_img_new1_png);    // assets\new1.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
