// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT TextArea1

lv_obj_t * ui_TextArea1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_TextArea1;
    cui_TextArea1 = lv_textarea_create(comp_parent);
    lv_obj_set_width(cui_TextArea1, 150);
    lv_obj_set_height(cui_TextArea1, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(cui_TextArea1, 37);
    lv_obj_set_y(cui_TextArea1, -29);
    lv_obj_set_align(cui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_one_line(cui_TextArea1, true);
    lv_textarea_set_password_mode(cui_TextArea1, true);
    lv_obj_set_style_border_color(cui_TextArea1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_TextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_TextArea1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_TEXTAREA1_NUM);
    children[UI_COMP_TEXTAREA1_TEXTAREA1] = cui_TextArea1;
    lv_obj_add_event_cb(cui_TextArea1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_TextArea1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_TextArea1_create_hook(cui_TextArea1);
    return cui_TextArea1;
}

